name: bridge
description: "A new Flutter project."
publish_to: 'none'
 
version: 1.0.0+1
 
environment:
  sdk: ^3.7.2
 
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: 2.5.3
  http: ^1.2.0
  crypto: ^3.0.3
  image_picker: ^1.2.1
  url_launcher: ^6.3.2
  audioplayers: ^6.0.0
  path_provider: ^2.1.2
  path: ^1.9.0
  js: ^0.6.7
  awesome_dialog: ^3.3.0 # ダイアログ
  flutter_tts: ^4.2.3 # 読み上げ用
  flutter_stripe: ^12.1.1 # Stripe決済用
  flutter_stripe_web: ^7.1.1 # webでStripeを実施するようえ
  web_socket_channel: ^2.3.0
  share_plus: ^10.0.0
  image: ^4.1.7
  file_picker: ^10.3.7
  payjp_flutter: ^0.7.7 # Pay.jp決済用

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 
flutter:
  uses-material-design: true
 
  assets:
    - lib/01-images/
    - lib/07-ai-training/quiz_data.json
    
fonts:
  - family: NotoSansJP
    fonts:
      - asset: assets/fonts/NotoSansJP-Regular.otf
 
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
 
 